FROM alpine:3.18

WORKDIR /usr/src/app

RUN apk update && apk add firefox

RUN apt-get update && apt-get install -y python3

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py ./

COPY . .

# Run the Flask application
CMD [ "python3", "app.py"]
