FROM alpine:3.18

RUN apk update \
  && apk add firefox

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py ./

COPY . .

# Run the Flask application
CMD [ "python3", "app.py"]
